/**
 * Generated by scripts/pull-confirmations.mjs. Do not edit by hand.
 * One vote per device (its latest) over the last 90 days.
 * Run `npm run confirmations:pull` to refresh.
 */
import type { ConfirmationSummary } from "./confirmations";

export const CONFIRMATIONS_PULLED_AT_ISO: string | undefined = undefined;

export const confirmations: Record<string, ConfirmationSummary> = {};
